### ISSUE TITLE
Getting a profile for some symbols does nothing

### ISSUE THREAD

**Issue by ddotlic** [barchart/marketdata-api-js#3]
Users started reporting weird formatting of prices in the HTML5 chart product for _some_ symbols (yet everything worked fine for most of the other symbols).

The issue with more context demonstrating the problem is [this one](/barchart/marketdata-ui-js/issues/237).

The actual problem is that for the symbol in question `GMM.AX` I'm not getting anything back when I call `getProfile`. This reproduces with the latest (at this moment) version of the API which is 3.0.3.

If this helps, when I change the symbol from `TWTR` to `GMM.AX` the following gets traced to the console:

```
GO GMM.AX=s
Connection.js:516:5
STOP TWTR=Ssc
Connection.js:516:5
```

I suspect letters behind `=` indicate what to do - more the better? - so while for Twitter there is `Ssc` for the problematic symbol we get only `s` (hope this helps).

**Comment by ddotlic** [comment]
Has been fixed, then broken, then fixed again multiple times 😄

**Comment by bryaningl3** [comment]
OK ... I never saw this issue ... Generally speaking, there is only about a 20% chance I respond to an automated email (e.g. from JIRA or GitHub) ... But, there is a 99% chance I respond to emails from real humans ... So, if you enter a "ticket" or something, and I ignore it ... send me an email directly.

With respect to this issue:

1. We have gone through two major versions since this issue was entered. The code will have been refactored a few times. Let me know if you're still having problems.

2. The code for getting profiles (asynchronously from JERQ) is gnarly. It's possible it has a bug. At a minimum, I will add a timeout, rejecting the promise. This is needed because JERQ will not respond when it does not recognize a symbol -- we just get dead air (so the promise never resolves or rejects).

3. The letters after the equals sign (in the JERQ protocol) indicate what type of data we want to receive. The "S" indicates we want streaming data (quotes, trades, etc). The "s" indicates we want a single snapshot. The "c" indicates we want to subscribe to cumulative volume. So "GO AMM.AX=s" translates to "please send me one snapshot for AMM.AX (so that I can extract the profile metadata).

**Comment by ddotlic** [comment]
@bryaningl3 Don't worry about this, please note the date: this is October 2017 (!) 😃 

We've improved things considerably both in the library and in the chart. The developers of the site somehow stumbled upon this item before they've even contacted me 😄
